# AUTOGENERATED! DO NOT EDIT! File to edit: develop/utils/midifile.ipynb (unless otherwise specified).

__all__ = ['file2mf', 'mf2stream', 'is_empty_midi']

# Cell
"Transform functions for raw midi files"
from enum import Enum
import music21
from music21.midi import ChannelVoiceMessages

def file2mf(fp):
    mf = music21.midi.MidiFile()
    if isinstance(fp, bytes):
        mf.readstr(fp)
    else:
        mf.open(fp)
        mf.read()
        mf.close()
    return mf

def mf2stream(mf): return music21.midi.translate.midiFileToStream(mf)

def is_empty_midi(fp):
    if fp is None: return False
    mf = file2mf(fp)
    return not any([t.hasNotes() for t in mf.tracks])
